### ISSUE TITLE
pmml --> back to pkl

### ISSUE THREAD

**Issue by emclinden** [jpmml/jpmml-sklearn#100]
Is there any way to go from a pmml file back to a pkl (or something else useable by python) if the original pkl.z file used to generate pmml is no longer available. or is this a lost cause? :/ Thanks!

**Comment by vruusmann** [comment]
It's impossible to go back to the original Scikit-Learn pipeline object, because the conversion application restructures and reconceptualizes many operations.

It should be possible to generate a new, simplified Scikit-Learn pipeline. Alternatively, it should be possible to generate free-form Python code, which yields correct predictions but is not tied to Scikit-Learn API at all (eg. could use some custom Python function for binarizing categorical variables, not the standard `LabelBinarizer` transformation type). However, such PMML-to-Python translation tool doesn't exist yet.

See also https://stackoverflow.com/questions/55217392/read-pmml-using-sklearn2pmml
