### ISSUE TITLE
support for lightgbm.LGBMRanker and xgboost.XGBRanker

### ISSUE THREAD

**Issue by liyinxiao** [jpmml/jpmml-sklearn#105]

**Comment by vruusmann** [comment]
Depends on https://github.com/jpmml/jpmml-lightgbm/issues/3 and https://github.com/jpmml/jpmml-xgboost/issues/16

**Comment by liyinxiao** [comment]
I figured out this to get around it and support XGBRanker to pmml with minimum coding efforts. 
https://github.com/liyinxiao/XGBRankertoPMML

**Comment by vruusmann** [comment]
@liyinxiao How is your "fix" supposed to work technically? You are taking the booster object from a fitted `XGBRanker`, and then generating a new `XGBRegressor` wrapper for it. However, as far as I know, the name of the objective function (`rank:pairwise` or `rank:ndcg`) is still embedded inside the booster object, and the JPMML-XGBoost library still rejects it (something like "unsupported objective function name `rank:pairwise`").

I haven't implemented ranking for XGBoost and LightGBM, because I don't have a good test data set. Do you know any public dataset that could be used for integration testing?

**Comment by liyinxiao** [comment]
I am not aware of any public dataset. I used this to generate my pmml with my own dataset, and it passed validation with 100K data points. I modified jpmml-xgboost-1.3-SNAPSHOT.jar so that JPMML-XGBoost library will not reject the objective function (rank:pairwise or rank:ndcg) and basically it will treat it as a Regressor.

**Comment by vruusmann** [comment]
@liyinxiao Thanks for pointing out that ranking models are functionally equivalent to regression models. I've just released SkLearn2PMML version 0.47.2 to PyPI, which provides support for `XGBRanker` and `LGBMRanker`.
