### ISSUE TITLE
Support for `sklearn_pandas.transformers.FunctionTransformer`

### ISSUE THREAD

**Issue by wuangKKK** [jpmml/jpmml-sklearn#122]
java.lang.IllegalArgumentException: The transformer object (Python class sklearn_pandas.transformers.FunctionTransformer) is not a supported Transformer

How to solve this problem?

**Comment by vruusmann** [comment]
This class looks like a dummy wrapper for a Python function. As such, it cannot be converted into PMML (because Python functions cannot be pickled and so on).

You have two replacements:
1. [`sklearn.preprocessing.FunctionTransformer`](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.FunctionTransformer.html)
2. [`sklearn2pmml.preprocessing.ExpressionTransformer`]

Use the former when dealing with simple functions (eg. Numpy universal functions), and the latter for everything else.
