### ISSUE TITLE
[Feature Request] pmml->sklearn

### ISSUE THREAD

**Issue by manugarri** [jpmml/jpmml-sklearn#17]
In order for pmml-sklearn workflow to be fully useful there needs to be a way of turning PMML representations into scikit-learn models.

AFAIK, this functionality does not exist afaik in any sklearn - pmml library. This means the current flow is one directional.

**Comment by vruusmann** [comment]
The unidirectional workflow is a feature, not a bug. In practice, you want to move from more specialized representations to more generalized representations. For example, Scikit-Learn -> PMML -> native Java or Python application code.

In other words, it may be rational and desirable to generate Python application code based on PMML. Such application code would operate with Numpy primitives directly, without any assistance from the Scikit-Learn library.

**Comment by manugarri** [comment]
That might be the case for certain cases, but cannot be generalized for every use case, specially in environments with multidisciplinary teams working together and sharing models that have to be inspected.

In other words, how would you go and implement a pure python PMML based application?

**Comment by vruusmann** [comment]
In multidisciplinary fields, PMML acts as _lingua franca_ between teams.

There is no point in trying to translate R or Apache Spark ML models to Scikit-Learn (over PMML), because  their "native" representations are **_not_** compatible with one another. Also, the Scikit-Learn representation of models in very restrictive. It doesn't support even some of the most basic ML concepts, such as multi-split decision tree nodes.

**Comment by manugarri** [comment]
Well, lets agree to disagree.
