### ISSUE TITLE
Support for multi-output `KNeighborsRegressor` models

### ISSUE THREAD

**Issue by PFloyd0** [jpmml/jpmml-sklearn#172]
Sorry
There are some errors when I  convert my model into pmml.
It seems the data size has been changed but I do not know why.
<img width="510" alt="WeChat Screenshot_20220401112342" src="https://user-images.githubusercontent.com/73516559/161189553-488f6fb4-874e-48f4-954e-5994b90c9630.png">

Thank you!

**Comment by PFloyd0** [comment]
Ok, thank you very much. The input are four intensity values from bluetooth device and output is location information, so I need two coordinates. I still try to think how to convert the output. Anyway, thank you again for your help.

**Comment by vruusmann** [comment]
> The input are four intensity values from bluetooth device and output is location information, so I need two coordinates.

Your model is basically a giant look-up table?

You could use a helper object "location" (some unique integer). So, you'd first map from 4D to "location", and then from "location" to 2D.

The latter transformation could be implemented using the `PMMLPipeline.predict_transformer` attribute. You'd currently need two look-up tables there - one for the "location -> x" mapping, and another one to "location -> y" mapping.

**Comment by PFloyd0** [comment]
It works. Thank you very much!

**Comment by vruusmann** [comment]
> It works.

What works? The suggested work-around using `PMMLPipeline.predict_transformer`?

Anyway, KNN models are prime examples of the multi-output use case.

This is already well supported on the JPMML-Evaluator side. What is missing are some lines of code into the JPMML-Converter and JPMML-SkLearn libraries.

Will work on this already this spring. Don't close the issue, otherwise I might forget!
