### ISSUE TITLE
scikit-learn version

### ISSUE THREAD

**Issue by dfarren** [jpmml/jpmml-sklearn#193]
Hello everyone. Just one comment and a question:

The readme file shows a [dependency for scikit-learn 0.16.0 or newer. ](https://github.com/jpmml/jpmml-sklearn/blob/master/README.md?plain=1#L477)
However, the code checks for scikit-version [less or equal to 1.3.2.](https://github.com/jpmml/jpmml-sklearn/blob/master/pmml-sklearn/src/main/java/sklearn/Step.java#L40)

Are there any plans to support later scikit-learn versions?

Thanks

**Comment by vruusmann** [comment]
> The readme file shows a dependency for scikit-learn 0.16.0 or newer.
> However, the code checks for scikit-version less or equal to 1.3.2.

All correct - these are the **lower and upper bounds** of supported Scikit-Learn versions. In other words, the JPMML-SkLearn library should be able to parse and convert any Pickle file that has been produced over the past ~eight years, using Scikit-Learn version 0.16.X -- 1.3.X. Beat that!

> Are there any plans to support later scikit-learn versions?

Most definitely.

The support for Scikit-Learn 1.4.X is currently not available, because Scikit-Learn developers broke the `Pipeline._fit(X, y)` method signature. See https://github.com/jpmml/sklearn2pmml/issues/409
