### ISSUE TITLE
AdaBoostClassifier class not found

### ISSUE THREAD

**Issue by mohitbadwal** [jpmml/jpmml-sklearn#41]
Ensemble has AdaBoostRegressor but it does not have AdaBoostClassifier , what should be done?

**Comment by vruusmann** [comment]
This is intentional, because AdaBoostClassifier implements some pseudo-probabilistic classification algorithm (the predicted class and the predicted probability distribution do not "match").

I would suggest using some other boosting algorithm, such as XGBoost or LightGBM. They both provide excellent Scikit-Learn interoperability.
