### ISSUE TITLE
Passing Parameters to Custom Transformation Function

### ISSUE THREAD

**Issue by mohitbadwal** [jpmml/jpmml-sklearn#44]
Hi , I have a column with continuous values  , in pandas I can use pd.cut() to group it into bins . I  don't want to have the values in a separate file (as suggested in some other issues ).

`mapper = DataFrameMapper([('customer_id',LabelEncoder()),(['date1' ,'date2'],[customtransform_add(function='subtract-dates')])])`

Is there a way I can pass parameters to my own custom transformation function specifying the bins ? 
Any help would be great.

**Comment by vruusmann** [comment]
> I have a column with continuous values , in pandas I can use pd.cut() to group it into bins.

All data transformations that are applied via Pandas' methods (eg. `pandas.cut`) cannot be seen by the `sklearn2pmml` function. You should always identify and apply a corresponding Scikit-Learn data transformer (eg. there doesn't seem to be a proper bucketizer available, so your best bet is a sequence of `sklearn.preprocessing.Binarizer` transformations).

> (['date1' ,'date2'],[customtransform_add(function='subtract-dates')])

You can implement your own `DateDifference` transformer class using the [SkLearn2PMML-Plugin](https://github.com/jpmml/sklearn2pmml-plugin)  extension mechanism.

PMML has built-in support for basic date and time functions, so it's possible to directly subtract one date field from other date field (yields the number of days).

For example, the Java business logic of your `DateDifference` transformer could be this:
```Java
public class DateDifference extends Transformer {

  @Override
  public List<Feature> encodeFeatures(List<Feature> features, SkLearnEncoder encoder){
    Feature firstDate = features.get(0);
    Feature secondDate = features.get(1);
    
    Apply apply = PMMLUtil.createApply("-", firstDate.ref(), secondDate.ref());
    DerivedField derivedField = encoder.createDerivedField(FieldName.create("datediff"), OpType.CONTINUOUS, DataType.INTEGER, apply);

    return Collections.<Feature>singletonList(new ContinuousFeature(encoder, derivedField));
  }
}
```

**Comment by mohitbadwal** [comment]
Hi ,
Thanks for the reply ,sorry  my example was a bit off . If there's a way I can pass parameter to a custom function , I can do the rest.
So , if you take a simple case of exponentiation  , x to the power of  n, where x is the column , I can write 
`DataFrameMapper([  ('x', [customtransform_add(function='exponent')]  ])`

And hard code the value of n.
But if I don't want to hard code the value of n , is there a way I can pass it from my python program?
Binning is just one use case where I'll pass the binning intervals.

**Comment by vruusmann** [comment]
Check out the SkLearn2PMML-Plugin project. It provides a custom transformation `com.mycompany.Aggregator`, which can be ordered to apply different aggregation methods (one of "min", "max" or "mean") depending on the value of the `function` argument:
https://github.com/jpmml/sklearn2pmml-plugin/blob/master/src/main/python/com/mycompany/__init__.py

**Comment by chandimsett** [comment]
Thanks for adding the function. For my use case, I need to know how to pass the argument to a custom transformer function, from the PMMLPipeline mapper. To be more specific, how do I create a Data Frame mapper which enables me to pass an argument for the respective custom transformer function, so that it creates a <Constant> markup carrying my argument in the PMML file for my custom transformer.

**Comment by chandimsett** [comment]
Thanks for adding the function. For my use case, I need to know how to pass the argument to a custom transformer function, from the PMMLPipeline mapper. To be more specific, how do I create a Data Frame mapper which enables me to pass an argument for the respective custom transformer function, so that it creates a <Constant> markup carrying my argument in the PMML file for my custom transformer.
