### ISSUE TITLE
Supporting `sklearn.neural_network.MLPClassifier`

### ISSUE THREAD

**Issue by kevinjos** [jpmml/jpmml-sklearn#7]
Are there any plans to support PMML export of the sklearn multilayer perceptron classifier implementation?

https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/neural_network/multilayer_perceptron.py

**Comment by vruusmann** [comment]
MLP models can be very easily represented using the [NeuralNetwork] (http://dmg.org/pmml/v4-2-1/NeuralNetwork.html) element. The only limitation appears to be that PMML 4.2 does not know anything about the `relu` activation function, which is the default for `MLPClassifier` and `MLPRegressor`. However, the support for the `relu` will be available starting from PMML 4.3.

Where did those MLP models come from? Is it some SkLearn 0.18 thing? The list of model and transformation types for JPMML-SkLearn was compiled after SkLearn 0.16 and 0.17 [API reference] (http://scikit-learn.org/stable/modules/classes.html), which - as of today - doesn't mention MLP models.

**Comment by kevinjos** [comment]
The MLPClassifier was introduced into sklearn master on October 21, 2015.

sklearn 0.17.0 was released in November, 2015 and it looks like the MPLClassifier didn't make it in.

**Comment by kevinjos** [comment]
When is the PMML 4.3 release scheduled? Also, I suggest we could move forward on an implementation against 4.2 with the limitation that rectified linear units are not supported.

**Comment by vruusmann** [comment]
I have SkLearn 0.17.1 installed, and it still doesn't know anything about `MLPRegressor` and `MLPClassifier` classes:
```
import sklearn
print(sklearn.__version__)

from sklearn.neural_network import MLPRegressor, MLPClassifier
```

What's your setup?

**Comment by kevinjos** [comment]
These classes only exist on the master branch, thus require an install from a source checkout.  I ran `$ python scikit-learn/setup.py install` inside a python virtual environment where all of the dependencies were met.

Should I reach out to the sklearn mailing list to determine if the MLP implementation is stable and when it will be released?

**Comment by vruusmann** [comment]
I decided to implement the `MLPRegressor` class first: https://github.com/jpmml/jpmml-sklearn/commit/a2737f114b4da6b0c279bd8366e3c8383d6f5573

**Comment by vruusmann** [comment]
The `relu` activation function in the context of PMML 4.3 can be tracked here (requires registration): http://mantis.dmg.org/view.php?id=145

It looks like a done deal. So, it shouldn't be a problem if it's pre-emptively introduced to the [JPMML-Model] (https://github.com/jpmml/jpmml-model) library, and propagated through the rest of the JPMML technology stack.

**Comment by kevinjos** [comment]
Is a pull request for the [JPMML-Evaluator](https://github.com/jpmml/jpmml-evaluator) and [JPMML-Model](https://github.com/jpmml/jpmml-model) libraries welcome? If so, I am happy to begin work on this.

**Comment by vruusmann** [comment]
The `relu` activation function is a rather trivial piece of functionality, which could be implemented across the JPMML stack (from the JPMML-Model class model to JPMML-SkLearn producer, to JPMML-Evaluator consumer) in less than 10 lines of code.

What's keeping me from implementing it is that I would strongly prefer to introduce it not as a one-time hack,  but as the first member of "JPMML extensions" framework. The latter needs some thinking and design, because it will have serious impact on the overall utility of the JPMML stack in handling custom ML workflow representation needs.

The first release of the "JPMML extensions" framework is at least a month away. If you need the `relu` activation function sooner than that, then you'll be better off rolling on your own.
