### ISSUE TITLE
TypeCheckException In targetField for RandomForest

### ISSUE THREAD

**Issue by okoutb** [jpmml/jpmml-sklearn#75]
Hello,
I'm using Python-trained ExtraTreeRegressor (n_estimators=10, max_depth=10) to predict a single double and get an error when trying to evaluate:

```
org.jpmml.evaluator.TypeCheckException: Expected double value, got missing value (null)

	at org.jpmml.evaluator.TypeUtil.toDouble(TypeUtil.java:687)
	at org.jpmml.evaluator.TypeUtil.cast(TypeUtil.java:466)
	at org.jpmml.evaluator.mining.MiningModelUtil.aggregateValues(MiningModelUtil.java:75)
	at org.jpmml.evaluator.mining.MiningModelEvaluator.evaluateRegression(MiningModelEvaluator.java:271)
	at org.jpmml.evaluator.mining.MiningModelEvaluator.evaluate(MiningModelEvaluator.java:233)
	at org.jpmml.evaluator.mining.MiningModelEvaluator.evaluate(MiningModelEvaluator.java:205)
	at PMMLEstimator.predict(PMMLEstimator.java:84)
	at PMMLEstimator.getPMMLEstimation(PMMLEstimator.java:72)
```

I have a single target value ("y") that the jpmml reads successfully:
`System.out.println(evaluator.getTargetFields()) 
`
Prints: 

> [TargetField{name=y, dataType=DOUBLE, opType=CONTINUOUS}]

But 
`evaluator.getTargetFields().get(0).target` is null

This is the function to create evaluator:
```
    private Evaluator createEvaluatorObj(PMML pmmlObj) {
        ModelEvaluatorFactory modelEvaluatorFactory = ModelEvaluatorFactory.newInstance();

        ValueFactoryFactory valueFactoryFactory = ReportingValueFactoryFactory.newInstance();
        modelEvaluatorFactory.setValueFactoryFactory(valueFactoryFactory);
        return modelEvaluatorFactory.newModelEvaluator(pmmlObj);
    }
```

This is the beginning of my PMML file:

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<PMML xmlns="http://www.dmg.org/PMML-4_3" version="4.3">
	<Header>
		<Application name="JPMML-SkLearn" version="1.5-SNAPSHOT"/>
	</Header>
	<DataDictionary>
		<DataField name="y" optype="continuous" dataType="double"/>
		<DataField name="feat1" optype="continuous" dataType="float"/>
```

**Comment by vruusmann** [comment]
> I have a single target value ("y") that the jpmml reads successfully:
> System.out.println(evaluator.getTargetFields())

The method `org.jpmml.evaluator.Evaluator#getTargetFields()` gives you target field **_declarations_** in the form of a list of `org.jpmml.evaluator.TargetField` objects.

> evaluator.getTargetFields().get(0).target is null

The Java field `org.jpmml.evaluator.TargetField#target` has private access. You really have no business with it.

> and get an error when trying to evaluate

Random forest model is a collection of decision tree models. This error means that the value of the random forest model cannot be computed, because on of the member decision tree models has produced a missing value.

The most common reason for this is that your input data record contains missing values (ie. is incomplete). Scikit-Learn's `RandomForestRegressor` would also crash if you executed it with a data matrix that contains missing values.
